### ISSUE TITLE
Problem running GPU sessions concurrently

### ISSUE THREAD

**Issue by jcberentsen** [tensorflow/haskell#158]
Using the procedure outlined in #157 I try to run two experiments concurrently using `Control.Concurrent.Async.concurrently experiment1 experiment2`

I log summaries to different filenames.

Running the experiments infividually works fine, but concurrently, various problems occur:

Sometimes I get:
```
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0)
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Infinity in summary histogram for: DecoderDecoder/HistogramSummary_193
         [[Node: DecoderDecoder/HistogramSummary_193 = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](DecoderDecoder/Const_192, DecoderDecoder/ReadVariableOp_186)]]
```

Other times:
```
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0)
E tensorflow/stream_executor/cuda/cuda_event.cc:49] Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_ADDRESS
F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:198] Unexpected Event status: 1
E tensorflow/stream_executor/cuda/cuda_event.cc:49] Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_ADDRESS
F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:198] Unexpected Event status: 1
```

Where the program aborts (I was running in ghci, but this problem killed even ghci)

I do use a wrapper around runSession to allow sharing of the GPU memory like this:
`TF.runSessionWithOptions (def & TF.sessionConfig .~ (def & TF.gpuOptions .~ (def & TF.allowGrowth .~ True)))` so I don't think this is about memory allocation.

**Comment by fkm3** [comment]
These issues seem related:
https://github.com/tensorflow/tensorflow/issues/9205
https://github.com/tensorflow/serving/issues/335

The fix for them was committed a while ago (https://github.com/caisq/tensorflow/commit/fccaac3d1bf1391756fae67f1979afe598d10ed1) but tensorflow-haskell is still using a really old version. Maybe we just need to update?

**Comment by blackgnezdo** [comment]
Upgrading is a good idea in any case. Anybody interested in doing it?

**Comment by fkm3** [comment]
https://github.com/tensorflow/haskell/pull/161

**Comment by fkm3** [comment]
I've updated master to tensorflow 1.3. Can you try again on the new version?

**Comment by jcberentsen** [comment]
Thanks, I'll try!

tor. 19. okt. 2017 kl. 19:52 skrev fkm3 <notifications@github.com>:

**Comment by jcberentsen** [comment]
Together with updated #157 I got this working! Great, thanks! Resolved
